In [ ]:
import torch
print(torch.__version__)

2.6.0+cu124


In [ ]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available! Using CPU.")

GPU not available! Using CPU.


## Tensors

In [ ]:
  #using empty
  x = torch.empty(2, 3)
  print(type(x))
  print(x)

<class 'torch.Tensor'>
tensor([[1.8352e-15, 4.5696e-41, 1.8352e-15],
        [4.5696e-41, 4.4842e-44, 0.0000e+00]])


In [ ]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.rand(2, 3)

tensor([[0.0431, 0.1649, 0.7530],
        [0.8912, 0.9700, 0.9757]])

In [ ]:
torch.manual_seed(69)
torch.rand(2, 3)

tensor([[0.8398, 0.8042, 0.1213],
        [0.5309, 0.6646, 0.4077]])

In [ ]:
torch.manual_seed(69)
torch.rand(2, 3)

tensor([[0.8398, 0.8042, 0.1213],
        [0.5309, 0.6646, 0.4077]])

In [ ]:
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.linspace(0, 10, 12)

tensor([ 0.0000,  0.9091,  1.8182,  2.7273,  3.6364,  4.5455,  5.4545,  6.3636,
         7.2727,  8.1818,  9.0909, 10.0000])

In [ ]:
torch.eye(3, 3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
torch.full((3, 3), 2)

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

## Tensor Shapes

In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 1, 0]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
print("x datatype = ", x.dtype)
torch.rand_like(x, dtype=torch.float)

x datatype =  torch.int64


tensor([[0.8741, 0.0560, 0.9659],
        [0.0073, 0.3628, 0.4197]])

## Mathematical Operations
### Scalar Operations

In [ ]:
x = torch.rand(3, 3)
x

tensor([[0.6444, 0.0099, 0.5925],
        [0.9631, 0.6958, 0.9157],
        [0.5523, 0.2344, 0.3262]])

In [ ]:
# addition
x + 3

tensor([[3.6444, 3.0099, 3.5925],
        [3.9631, 3.6958, 3.9157],
        [3.5523, 3.2344, 3.3262]])

In [ ]:
# subtraction
x - 2

tensor([[-1.3556, -1.9901, -1.4075],
        [-1.0369, -1.3042, -1.0843],
        [-1.4477, -1.7656, -1.6738]])

In [ ]:
# multiplication
x * 2

tensor([[1.2888, 0.0199, 1.1850],
        [1.9262, 1.3915, 1.8313],
        [1.1047, 0.4688, 0.6525]])

In [ ]:
# division
x / 2

tensor([[0.3222, 0.0050, 0.2963],
        [0.4815, 0.3479, 0.4578],
        [0.2762, 0.1172, 0.1631]])

In [ ]:
# integer division
x // 2

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# mod
x % 0.2

tensor([[0.0444, 0.0099, 0.1925],
        [0.1631, 0.0958, 0.1157],
        [0.1523, 0.0344, 0.1262]])

In [ ]:
# power
x ** 2

tensor([[4.1524e-01, 9.8763e-05, 3.5106e-01],
        [9.2754e-01, 4.8408e-01, 8.3843e-01],
        [3.0508e-01, 5.4939e-02, 1.0643e-01]])

### Element-wise Operations

In [ ]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)
print(a)
print(b)

tensor([[0.4521, 0.7020, 0.6274],
        [0.0945, 0.8525, 0.3572]])
tensor([[0.7492, 0.3579, 0.5453],
        [0.8171, 0.0570, 0.4560]])


In [ ]:
# addition
a + b

tensor([[1.2013, 1.0599, 1.1726],
        [0.9116, 0.9095, 0.8132]])

In [ ]:
# subtraction
a - b

tensor([[-0.2971,  0.3440,  0.0821],
        [-0.7226,  0.7954, -0.0987]])

In [ ]:
# multiplication
a * b

tensor([[0.3387, 0.2513, 0.3421],
        [0.0772, 0.0486, 0.1629]])

In [ ]:
# division
a / b

tensor([[ 0.6035,  1.9611,  1.1506],
        [ 0.1157, 14.9434,  0.7835]])

In [ ]:
# integer division
a // b

tensor([[ 0.,  1.,  1.],
        [ 0., 14.,  0.]])

In [ ]:
# mod
a % b

tensor([[0.4521, 0.3440, 0.0821],
        [0.0945, 0.0538, 0.3572]])

In [ ]:
# power
a ** b

tensor([[0.5517, 0.8810, 0.7755],
        [0.1455, 0.9909, 0.6254]])

In [ ]:
c = torch.tensor([1, -2, 2, -5])

In [ ]:
torch.abs(c)

tensor([1, 2, 2, 5])

In [ ]:
torch.neg(c)

tensor([-1,  2, -2,  5])

In [ ]:
d = torch.tensor([1.4, 4.2, -3.5, 2.7])

In [ ]:
torch.round(d)

tensor([ 1.,  4., -4.,  3.])

In [ ]:
torch.ceil(d)

tensor([ 2.,  5., -3.,  3.])

In [ ]:
torch.floor(d)

tensor([ 1.,  4., -4.,  2.])

In [ ]:
torch.clamp(d, min=-2, max=3)

tensor([ 1.4000,  3.0000, -2.0000,  2.7000])

### Reduction Operations

In [ ]:
e = torch.randint(size=(2, 3), low=0, high=10, dtype=torch.float)
e

tensor([[6., 2., 7.],
        [6., 7., 3.]])

In [ ]:
# sum
torch.sum(e)

tensor(31.)

In [ ]:
# sum columns
torch.sum(e, dim=1)

tensor([15., 16.])

In [ ]:
# sum rows
torch.sum(e, dim=0)

tensor([12.,  9., 10.])

In [ ]:
# mean
torch.mean(e)

tensor(5.1667)

In [ ]:
# mean rows
torch.mean(e, dim=0)

tensor([6.0000, 4.5000, 5.0000])

In [ ]:
# median
torch.median(e)

tensor(6.)

In [ ]:
# max and min
print("max =", torch.max(e))
print("min =", torch.min(e))

max = tensor(7.)
min = tensor(2.)


In [ ]:
# product
torch.prod(e)

tensor(10584.)

In [ ]:
# standard deviation
torch.std(e)

tensor(2.1370)

In [ ]:
# variance
torch.var(e)

tensor(4.5667)

In [ ]:
# argmax - idx(flattened) of max element
torch.argmax(e)

tensor(2)

In [ ]:
# argmin - idx(flattened) of min element
torch.argmin(e)

tensor(1)

### Matrix Operations

In [ ]:
f = torch.randint(size=(2, 3), low=0, high=10, dtype=torch.float)
g = torch.randint(size=(3, 2), low=0, high=10, dtype=torch.float)
print(f)
print(g)

tensor([[7., 6., 5.],
        [2., 9., 4.]])
tensor([[1., 4.],
        [1., 5.],
        [2., 1.]])


In [ ]:
# matrix multiplication
torch.matmul(f, g)

tensor([[23., 63.],
        [19., 57.]])

In [ ]:
u = torch.tensor([1, 2, 3])
v = torch.tensor([5, 3, 1])

# dot product
torch.dot(u, v)

tensor(14)

In [ ]:
# transpose
print(torch.transpose(f, 0, 1))
# OR just <f.T>
print(f.T)

tensor([[7., 2.],
        [6., 9.],
        [5., 4.]])
tensor([[7., 2.],
        [6., 9.],
        [5., 4.]])


In [ ]:
h = torch.randint(size=(3, 3), low=0, high=10, dtype=torch.float)
h

tensor([[4., 7., 2.],
        [5., 0., 5.],
        [8., 4., 3.]])

In [ ]:
# determinant
torch.det(h)

tensor(135.)

In [ ]:
# inverse
torch.inverse(h)

tensor([[-0.1481, -0.0963,  0.2593],
        [ 0.1852, -0.0296, -0.0741],
        [ 0.1481,  0.2963, -0.2593]])

### Comparison Operations

In [ ]:
i = torch.randint(size=(2, 3), low=0, high=10, dtype=torch.float)
j = torch.randint(size=(2, 3), low=0, high=10, dtype=torch.float)

print(i)
print(j)

tensor([[2., 9., 4.],
        [6., 5., 4.]])
tensor([[5., 9., 0.],
        [1., 3., 9.]])


In [ ]:
# greater than
i > j

tensor([[False, False,  True],
        [ True,  True, False]])

In [ ]:
# less than
i < j

tensor([[ True, False, False],
        [False, False,  True]])

In [ ]:
# greater than or equal to
i >= j

tensor([[False,  True,  True],
        [ True,  True, False]])

In [ ]:
# less than or equal to
i <= j

tensor([[ True,  True, False],
        [False, False,  True]])

In [ ]:
# equal to
i == j

tensor([[False,  True, False],
        [False, False, False]])

In [ ]:
# not equal to
i != j

tensor([[ True, False,  True],
        [ True,  True,  True]])

### Special Functions

In [ ]:
k = torch.randint(size=(2, 3), high=10, low=0, dtype=torch.float)
print(k)

tensor([[1., 8., 3.],
        [1., 7., 0.]])


In [ ]:
# log
torch.log(k)

tensor([[0.0000, 2.0794, 1.0986],
        [0.0000, 1.9459,   -inf]])

In [ ]:
# exponent
torch.exp(k)

tensor([[2.7183e+00, 2.9810e+03, 2.0086e+01],
        [2.7183e+00, 1.0966e+03, 1.0000e+00]])

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[1.0000, 2.8284, 1.7321],
        [1.0000, 2.6458, 0.0000]])

In [ ]:
# sigmoid
torch.sigmoid(k)

tensor([[0.7311, 0.9997, 0.9526],
        [0.7311, 0.9991, 0.5000]])

In [ ]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.5000, 0.7311, 0.9526],
        [0.5000, 0.2689, 0.0474]])

In [ ]:
# relu
torch.relu(k)

tensor([[1., 8., 3.],
        [1., 7., 0.]])

### Inplace Operations

In [ ]:
m = torch.rand(2, 3)
n = torch.rand(2, 3)

print(m)
print(n)

tensor([[0.1089, 0.3925, 0.9651],
        [0.8191, 0.8030, 0.2029]])
tensor([[0.2073, 0.0954, 0.4212],
        [0.4838, 0.3973, 0.4797]])


In [ ]:
m.add_(n)

tensor([[0.3161, 0.4879, 1.3862],
        [1.3029, 1.2004, 0.6825]])

In [ ]:
m

tensor([[0.3161, 0.4879, 1.3862],
        [1.3029, 1.2004, 0.6825]])

In [ ]:
n

tensor([[0.2073, 0.0954, 0.4212],
        [0.4838, 0.3973, 0.4797]])

In [ ]:
m.relu_()

tensor([[0.3161, 0.4879, 1.3862],
        [1.3029, 1.2004, 0.6825]])

### Copying a Tensor

In [ ]:
a = torch.rand(2, 3)
a

tensor([[0.7069, 0.1273, 0.1206],
        [0.6707, 0.4570, 0.1266]])

In [ ]:
# b is a shallow copy (it references a)
b = a

In [ ]:
b

tensor([[0.7069, 0.1273, 0.1206],
        [0.6707, 0.4570, 0.1266]])

In [ ]:
print(id(a))
print(id(b))

140054899007056
140054899007056


In [ ]:
# deep copy
b = a.clone()

In [ ]:
print(id(a))
print(id(b))

140054899007056
140054899347568


## Tensor Operations on GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [ ]:
# creating a new tensor on GPU
torch.rand((2, 3), device=device)

tensor([[0.2565, 0.3538, 0.9080],
        [0.8392, 0.7151, 0.3346]], device='cuda:0')

In [ ]:
# moving an existing tensor to GPU
x = torch.rand(2, 3)
x

tensor([[0.9960, 0.2493, 0.3987],
        [0.3688, 0.7745, 0.4019]])

In [ ]:
y = x.to(device)

In [ ]:
y + 5

tensor([[5.9960, 5.2493, 5.3987],
        [5.3688, 5.7745, 5.4019]], device='cuda:0')

In [ ]:
# CPU vs GPU comparison for Tensor Operations
import time

size = 10000

matrix_cpu1 = torch.rand(size, size)
matrix_cpu2 = torch.rand(size, size)

start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

matrix_gpu1 = matrix_cpu1.to(device)
matrix_gpu2 = matrix_cpu2.to(device)

start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time:.4f} seconds")

print(f"\nspeedup: {cpu_time/gpu_time}")

Time on CPU: 18.9046 seconds
Time on GPU: 0.2097 seconds

speedup: 90.15004439755194


### Reshaping Tensors

In [ ]:
a = torch.ones(4, 4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# reshape
a.reshape(2, 2, 2, 2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b = torch.rand(2, 3, 4)
b

tensor([[[0.0274, 0.3974, 0.9084, 0.0116],
         [0.1609, 0.7960, 0.4286, 0.0057],
         [0.6249, 0.4231, 0.7488, 0.9464]],

        [[0.7335, 0.6118, 0.3569, 0.5799],
         [0.7854, 0.9554, 0.2827, 0.4520],
         [0.4635, 0.2112, 0.7998, 0.7972]]])

In [ ]:
# permute
b.permute(2, 0, 1).shape

torch.Size([4, 2, 3])

In [ ]:
# unsqueeze - adds a new dimension
c = torch.rand(226, 226, 3)   # typical image size
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [ ]:
# squeeze - opposite of unsqueeze
d = torch.rand(1, 20)
d.squeeze(0).shape

torch.Size([20])

## NumPy and Pytorch

In [ ]:
import numpy as np

In [ ]:
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

In [ ]:
b = a.numpy()
b

array([1, 2, 3])

In [ ]:
print(type(a))
print(type(b))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


In [ ]:
c = np.array([1, 2, 3])
c

array([1, 2, 3])

In [ ]:
d = torch.from_numpy(c)
d

tensor([1, 2, 3])

In [ ]:
print(type(c))
print(type(d))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>
